// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayer.Data;

#nullable disable

namespace MusicPlayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MusicPlayer.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("MusicPlayer.Models.Song", b =>
                {
                    b.OwnsOne("MusicPlayer.Models.SongMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("SongId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Album")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Bitrate")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Channels")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Genre")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("SampleRate")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SongId");

                            b1.ToTable("Songs");

                            b1.WithOwner()
                                .HasForeignKey("SongId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
