// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayer.database;

#nullable disable

namespace MusicPlayer.Database.Migrations.Local
{
    [DbContext(typeof(LocalMusicPlayerContext))]
    [Migration("20250608141915_InitialLocal")]
    partial class InitialLocal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("MusicPlayer.database.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("album");

                    b.Property<string>("AlbumImage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("album_image");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artist");

                    b.Property<string>("AudioDownloadPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("audio_download_path");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("audio_path");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration");

                    b.Property<string>("Releasedate")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("songs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
